# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2d13540220a83798e83d2ea89df00bc381fbd7f7fdcc40c964482435ca82831616625adbec3957b5b132fe7ae5ecdbebc3e07b9d2799c22bf7327642efa9828

test:
  secret_key_base: 3c700b5cfab35538ab19e90a2ac25724fc10f7922d6b84730a45e1534d3ef6e18f28ad60cb49dc53c153883f14048fe3a0e19aa23ef5861b3256a705706d4fdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
